DELETE FROM Reglas
GO
INSERT INTO Reglas VALUES ('EMPLEADOS', '', 'ACTIVO');
INSERT INTO Reglas VALUES ('PRODUCTOS', '', 'ACTIVO');
INSERT INTO Reglas VALUES ('MESAS', '', 'ACTIVO');
INSERT INTO Reglas VALUES ('VENTAS', '', 'ACTIVO');
INSERT INTO Reglas VALUES ('ESTADISTICAS', '', 'ACTIVO');