DELETE FROM Reglas
INSERT INTO Reglas VALUES ('EMPLEADOS', 'ACTIVO');
INSERT INTO Reglas VALUES ('PRODUCTOS', 'ACTIVO');
INSERT INTO Reglas VALUES ('MESAS', 'ACTIVO');
INSERT INTO Reglas VALUES ('VENTAS', 'ACTIVO');
INSERT INTO Reglas VALUES ('ESTADISTICAS', 'ACTIVO');

INSERT INTO Reglas_usuario 
SELECT Id_regla, 2, Estado_regla FROM Reglas 