DELETE FROM Catalogo
GO
INSERT INTO Catalogo 
VALUES(0,'TIPOS DE USUARIOS');
GO
DECLARE @IdPadre int = SCOPE_IDENTITY();

INSERT INTO Catalogo 
VALUES(@IdPadre,'ADMINISTRADOR');

INSERT INTO Catalogo 
VALUES(@IdPadre,'MESERO');

INSERT INTO Catalogo 
VALUES(@IdPadre,'COCINERO');

INSERT INTO Catalogo 
VALUES(@IdPadre,'CAJERO');

INSERT INTO Catalogo 
VALUES(@IdPadre,'CLIENTE');
GO
INSERT INTO Catalogo 
VALUES(0,'TIPO PEDIDOS');
GO
DECLARE @IdPadre int = SCOPE_IDENTITY();

INSERT INTO Catalogo 
VALUES(@IdPadre,'MESA');

INSERT INTO Catalogo 
VALUES(@IdPadre,'DOMICILIO');
GO
INSERT INTO Catalogo 
VALUES(0,'TIPOS DE PRODUCTOS');
GO
DECLARE @IdPadreProductos int = SCOPE_IDENTITY();
INSERT INTO Catalogo 
VALUES(@IdPadreProductos,'TIPOS PLATOS');
DECLARE @IdPadre int = SCOPE_IDENTITY();

INSERT INTO Catalogo 
VALUES(@IdPadre,'OTRO');

INSERT INTO Catalogo 
VALUES(@IdPadre,'PLATO CARTA');

INSERT INTO Catalogo 
VALUES(@IdPadre,'PLATO FUERTE');

INSERT INTO Catalogo 
VALUES(@IdPadre,'COMIDAS RAPIDAS');

INSERT INTO Catalogo 
VALUES(@IdPadre,'ADICIONES');

INSERT INTO Catalogo 
VALUES(@IdPadreProductos,'TIPOS BEBIDAS');
SET @IdPadre = SCOPE_IDENTITY();

INSERT INTO Catalogo 
VALUES(@IdPadre,'LIMONADA');

INSERT INTO Catalogo 
VALUES(@IdPadre,'JUGOS');

INSERT INTO Catalogo 
VALUES(@IdPadre,'CERVEZAS');

INSERT INTO Catalogo 
VALUES(@IdPadreProductos,'COMIDA VARIA');
SET @IdPadre = SCOPE_IDENTITY();

INSERT INTO Catalogo 
VALUES(@IdPadre,'SALCHICHAS');

INSERT INTO Catalogo 
VALUES(@IdPadre,'PAN');

INSERT INTO Catalogo 
VALUES(@IdPadre,'RIPIO');

INSERT INTO Catalogo 
VALUES(@IdPadreProductos,'ARTICULOS');
SET @IdPadre = SCOPE_IDENTITY();

INSERT INTO Catalogo 
VALUES(@IdPadre,'PRENDAS');

INSERT INTO Catalogo 
VALUES(@IdPadre,'MOBILIARIO');

INSERT INTO Catalogo 
VALUES(@IdPadre,'TIENDA');

GO
INSERT INTO Catalogo 
VALUES(0,'TIPOS DE FACTURACION');
GO
DECLARE @IdPadre int = SCOPE_IDENTITY();
INSERT INTO Catalogo
VALUES (@IdPadre, 'SUBTOTAL')

INSERT INTO Catalogo
VALUES (@IdPadre, 'TOTAL')

INSERT INTO Catalogo
VALUES (@IdPadre, 'DESCUENTO')

INSERT INTO Catalogo
VALUES (@IdPadre, 'DESECHABLE')

INSERT INTO Catalogo
VALUES (@IdPadre, 'DOMICILIO')

INSERT INTO Catalogo
VALUES (@IdPadre, 'PROPINA')

