DELETE FROM Catalogo
GO
INSERT INTO Catalogo 
VALUES(0,'TIPO DE USUARIOS');
GO
DECLARE @IdPadre int = SCOPE_IDENTITY();

INSERT INTO Catalogo 
VALUES(@IdPadre,'ADMINISTRADOR');

INSERT INTO Catalogo 
VALUES(@IdPadre,'MESERO');

INSERT INTO Catalogo 
VALUES(@IdPadre,'COCINERO');

INSERT INTO Catalogo 
VALUES(@IdPadre,'CAJERO');

INSERT INTO Catalogo 
VALUES(@IdPadre,'CLIENTE');
GO
INSERT INTO Catalogo 
VALUES(0,'TIPO PEDIDOS');
GO
DECLARE @IdPadre int = SCOPE_IDENTITY();

INSERT INTO Catalogo 
VALUES(@IdPadre,'MESA');

INSERT INTO Catalogo 
VALUES(@IdPadre,'DOMICILIO');
GO
INSERT INTO Catalogo 
VALUES(0,'TIPOS PLATOS');
GO
DECLARE @IdPadre int = SCOPE_IDENTITY();

INSERT INTO Catalogo 
VALUES(@IdPadre,'OTRO');

INSERT INTO Catalogo 
VALUES(@IdPadre,'PLATO CARTA');

INSERT INTO Catalogo 
VALUES(@IdPadre,'PLATO FUERTE');

INSERT INTO Catalogo 
VALUES(@IdPadre,'COMIDAS RAPIDAS');

INSERT INTO Catalogo 
VALUES(@IdPadre,'ADICIONES');
GO

