DELETE FROM Catalogo
GO
INSERT INTO Catalogo 
VALUES(0,'TIPO DE USUARIOS');
GO
DECLARE @IdPadre int = SCOPE_IDENTITY();

INSERT INTO Catalogo 
VALUES(@IdPadre,'ADMINISTRADOR');

INSERT INTO Catalogo 
VALUES(@IdPadre,'MESERO');

INSERT INTO Catalogo 
VALUES(@IdPadre,'COCINERO');

INSERT INTO Catalogo 
VALUES(@IdPadre,'CAJERO');
GO
