//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentacionRestaurant.ServicesRestaurant {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class ConfigRestaurant : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigRestaurant defaultInstance = ((ConfigRestaurant)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigRestaurant())));
        
        public static ConfigRestaurant Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CantidadMesas {
            get {
                return ((int)(this["CantidadMesas"]));
            }
            set {
                this["CantidadMesas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsModuloDomicilio {
            get {
                return ((bool)(this["IsModuloDomicilio"]));
            }
            set {
                this["IsModuloDomicilio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsResizeMesas {
            get {
                return ((bool)(this["IsResizeMesas"]));
            }
            set {
                this["IsResizeMesas"] = value;
            }
        }
    }
}
